Repository mono/api-doc-tools, pull requests merged in 2018-08, with the labels that each got.

#306 Added a flag to instruct the export-msxdoc command to be quiet
  mdoc/Mono.Documentation/monodocs2slashdoc.cs
Labels: enhancement

#305 Added a new function to make sure a file is deleted on slower HDDs
  mdoc/Mono.Documentation/MDocUpdater.cs
  mdoc/Mono.Documentation/MdocFile.cs
  mdoc/Mono.Documentation/Updater/Frameworks/FrameworkIndex.cs
Labels: enhancement

#343 removed the exception flag on integration tests.
  mdoc/Makefile
  mdoc/Mono.Documentation/exceptions.cs
  mdoc/Test/en.expected.delete/Mono.DocTest.Generic/GenericBase`1.xml
  mdoc/Test/en.expected.delete/Mono.DocTest/DocAttribute.xml
  mdoc/Test/en.expected.delete/Mono.DocTest/DocValueType.xml
  mdoc/Test/en.expected.delete/Mono.DocTest/UseLists.xml
  mdoc/Test/en.expected.delete/Mono.DocTest/Widget.xml
  mdoc/Test/en.expected.delete/System/Array.xml
  mdoc/Test/en.expected.delete/System/Environment.xml
  mdoc/Test/en.expected.importecmadoc/System/Array.xml
  mdoc/Test/en.expected.importecmadoc/System/Environment.xml
  mdoc/Test/en.expected.importslashdoc/Mono.DocTest.Generic/GenericBase`1.xml
  mdoc/Test/en.expected.importslashdoc/Mono.DocTest/DocAttribute.xml
  mdoc/Test/en.expected.importslashdoc/Mono.DocTest/DocValueType.xml
  mdoc/Test/en.expected.importslashdoc/Mono.DocTest/UseLists.xml
  mdoc/Test/en.expected.importslashdoc/Mono.DocTest/Widget.xml
  mdoc/Test/en.expected.importslashdoc/System/Array.xml
  mdoc/Test/en.expected.importslashdoc/System/Environment.xml
  mdoc/Test/en.expected.since/Mono.DocTest.Generic/GenericBase`1.xml
  mdoc/Test/en.expected.since/Mono.DocTest/DocAttribute.xml
  mdoc/Test/en.expected.since/Mono.DocTest/DocValueType.xml
  mdoc/Test/en.expected.since/Mono.DocTest/UseLists.xml
  mdoc/Test/en.expected.since/Mono.DocTest/Widget.xml
  mdoc/Test/en.expected.since/System/Array.xml
  mdoc/Test/en.expected.since/System/Environment.xml
  mdoc/Test/en.expected/Mono.DocTest.Generic/GenericBase`1.xml
  mdoc/Test/en.expected/Mono.DocTest/DocAttribute.xml
  mdoc/Test/en.expected/Mono.DocTest/DocValueType.xml
  mdoc/Test/en.expected/Mono.DocTest/UseLists.xml
  mdoc/Test/en.expected/Mono.DocTest/Widget.xml
  mdoc/Test/en.expected/System/Array.xml
  mdoc/Test/en.expected/System/Environment.xml
  mdoc/Test/html.expected-with-array-extension/Mono.DocTest.Generic/GenericBase`1.html
  mdoc/Test/html.expected-with-array-extension/Mono.DocTest/DocAttribute.html
  mdoc/Test/html.expected-with-array-extension/Mono.DocTest/DocValueType.html
  mdoc/Test/html.expected-with-array-extension/Mono.DocTest/UseLists.html
  mdoc/Test/html.expected-with-array-extension/Mono.DocTest/Widget.html
  mdoc/Test/html.expected-with-array-extension/System/Array.html
  mdoc/Test/html.expected-with-array-extension/System/Environment.html
  mdoc/Test/html.expected/Mono.DocTest.Generic/GenericBase`1.html
  mdoc/Test/html.expected/Mono.DocTest/DocAttribute.html
  mdoc/Test/html.expected/Mono.DocTest/DocValueType.html
  mdoc/Test/html.expected/Mono.DocTest/UseLists.html
  mdoc/Test/html.expected/Mono.DocTest/Widget.html
  mdoc/Test/html.expected/System/Array.html
  mdoc/Test/html.expected/System/Environment.html
  mdoc/Test/msxdoc-expected.importslashdoc.xml
  mdoc/mdoc.Test/Enumeration/CecilBaseTest.cs
  mdoc/mdoc.Test/Enumeration/EnumeratorTests.cs
  mdoc/mdoc.Test/Enumeration/ExceptionTests.cs
  mdoc/mdoc.Test/mdoc.Test.csproj
Labels: bug

#344 Added attribute support for array parameters.
  mdoc/Mono.Documentation/MDocUpdater.cs
  mdoc/Test/en.expected-fsharp/AbstractClasses+Shape2D.xml
  mdoc/Test/en.expected-fsharp/Customers.xml
  mdoc/Test/en.expected-fsharp/Delegates+Test1.xml
  mdoc/Test/en.expected-fsharp/Delegates.xml
  mdoc/Test/en.expected-fsharp/Extensions.xml
  mdoc/Test/en.expected-fsharp/Functions.xml
  mdoc/Test/en.expected-fsharp/Generics.xml
  mdoc/Test/en.expected-fsharp/Methods+SomeType.xml
  mdoc/Test/en.expected-fsharp/OperatorGlobalLevel.xml
  mdoc/Test/en.expected-fsharp/PatternMatching/PatternMatchingExamples.xml
  mdoc/Test/en.expected-fsharp/TypeExtensions.xml
  mdoc/Test/en.expected-fsharp/UnitsOfMeasure.xml
Labels: bug, enhancement
